apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: node-disk-load-fill
spec:
  experiments:
  - scope: node
    target: disk
    action : "fill"
    desc: "increase disk fill by names"
    matchers:
    - name: names
      value:
      - "ip-192-168-45-148.ec2.internal"
    - name: path
      value:
      - "/"
    - name: size
      value:
      - "50048"
